CREATE SEQUENCE IF NOT EXISTS company_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS operating_hours_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS services_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS customer_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS appointments_seq START WITH 1 INCREMENT BY 50;

-- ==========================================
-- TABLES
-- ==========================================
CREATE TABLE IF NOT EXISTS COMPANY (
                                       id BIGINT PRIMARY KEY,
                                       name VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL UNIQUE,
    plan VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
                             );
CREATE INDEX idx_nickname ON COMPANY(nickname);

CREATE TABLE IF NOT EXISTS INTERVALS (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         start TIME,
                                         finish TIME,
                                         lunch_start TIME,
                                         lunch_end TIME
);

CREATE TABLE IF NOT EXISTS USERS (
                                     id BIGINT PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             role VARCHAR(50) NOT NULL,
    company_id BIGINT REFERENCES COMPANY(id),
    interval_id BIGINT REFERENCES INTERVALS(id)
    );

CREATE TABLE IF NOT EXISTS OPERATING_HOURS (
                                               id BIGINT PRIMARY KEY,
                                               day_of_week SMALLINT NOT NULL,
                                               open TIME NOT NULL,
                                               close TIME NOT NULL,
                                               company_id BIGINT REFERENCES COMPANY(id)
    );

CREATE TABLE IF NOT EXISTS SERVICES (
                                        id BIGINT PRIMARY KEY,
                                        name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    price DECIMAL(19, 2) NOT NULL,
    duration INT NOT NULL,
    company_id BIGINT REFERENCES COMPANY(id)
    );

CREATE TABLE IF NOT EXISTS CUSTOMER (
                                        id BIGINT PRIMARY KEY,
                                        name VARCHAR(255) NOT NULL,
    phone_n VARCHAR(255) NOT NULL UNIQUE,
    company_id BIGINT REFERENCES COMPANY(id)
    );
CREATE INDEX idx_number ON CUSTOMER(phone_n);

CREATE TABLE IF NOT EXISTS APPOINTMENTS (
                                            id BIGINT PRIMARY KEY,
                                            scheduled TIMESTAMP NOT NULL,
                                            status VARCHAR(50) NOT NULL,
    company_id BIGINT REFERENCES COMPANY(id),
    user_id BIGINT REFERENCES USERS(id),
    customer_id BIGINT REFERENCES CUSTOMER(id),
    service_id BIGINT REFERENCES SERVICES(id)
    );

CREATE UNLOGGED TABLE IF NOT EXISTS CACHE_TB (
    key VARCHAR(255) PRIMARY KEY,
    json TEXT,
    exp_date TIMESTAMP
);

-- ==========================================
-- FUNCTIONS
-- ==========================================

CREATE OR REPLACE FUNCTION get_appointment(p_company_nickname VARCHAR, p_employee_name VARCHAR)
RETURNS TABLE (name VARCHAR, duration INT, scheduled TIMESTAMP) AS $$
BEGIN
    IF p_employee_name IS NULL OR TRIM(p_employee_name) = '' THEN
        RETURN QUERY
SELECT u.name, cs.name, s.duration, a.scheduled, a.status
FROM APPOINTMENTS a
         JOIN USERS u ON a.user_id = u.id
         JOIN SERVICES s ON a.service_id = s.id
         JOIN COMPANY c ON a.company_id = c.id
        JOIN CUSTOMER cs on a.customer_id = cs.id
WHERE c.nickname = p_company_nickname
  AND a.scheduled > CURRENT_TIMESTAMP;
ELSE
        RETURN QUERY
SELECT u.name, cs.name, s.duration, a.scheduled, a.status
FROM APPOINTMENTS a
         JOIN USERS u ON a.user_id = u.id
         JOIN SERVICES s ON a.service_id = s.id
         JOIN COMPANY c ON a.company_id = c.id
         JOIN CUSTOMER cs on a.customer_id = cs.id
WHERE c.nickname = p_company_nickname
  AND u.name = p_employee_name
  AND a.scheduled > CURRENT_TIMESTAMP;
END IF;
END;
$$ LANGUAGE plpgsql;