ALTER TABLE USERS ADD COLUMN PHONE_NUMBER VARCHAR(9)
ALTER TABLE USERS ADD COLUMN PUBLIC_ID UUID;

ALTER TABLE APPONTMENTS ADD COLUMN PUBLIC_ID UUID;
ALTER TABLE SERVICES ADD COLUMN  PUBLIC_ID UUID;

ALTER TABLE CUSTOMER ADD COLUMN PUBLIC_ID VARCHAR(255);
ALTER TABLE CUSTOMER ADD COLUMN EMAIL VARCHAR(255);
ALTER TABLE CUSTOMER ADD COLUMN TAX_ID VARCHAR(11);